const data = {
  products: [
    {
      _id: "1",
      name: "Rona Shirt 2020",
      image: "/images/prod1.jpg",
      price: 29.99,
      countInStock: 123,
      brand: "RandoBrand",
      rating: 4.5,
      numReviews: 18,
      description: "good stuff here",
    },
    {
      _id: "2",
      name: "Meh Shirt",
      image: "/images/prod2.jpg",
      price: 20.99,
      countInStock: 10,
      brand: "Zswift",
      rating: 4.5,
      numReviews: 10,
      description: "good stuff here",
    },
    {
      _id: "3",
      name: "Happy Shirt",
      image: "/images/prod3.jpg",
      price: 21.99,
      countInStock: 20,
      brand: "Rand",
      rating: 4.5,
      numReviews: 12,
      description: "good stuff here",
    },
    {
      _id: "4",
      name: "Boring Shirt",
      image: "/images/prod4.jpg",
      price: 9.99,
      countInStock: 0,
      brand: "Ranomadd",
      rating: 4.5,
      numReviews: 11,
      description: "good stuff here",
    },
    {
      _id: "5",
      name: "Questionable Shirt",
      image: "/images/prod5.jpg",
      price: 30.99,
      countInStock: 15,
      brand: "Nike",
      rating: 4.5,
      numReviews: 1,
      description: "good stuff here",
    },
    {
      _id: "6",
      name: "Fleek Shirt",
      image: "/images/prod6.jpg",
      price: 3.99,
      countInStock: 12,
      brand: "Adidas",
      rating: 4.5,
      numReviews: 17,
      description: "good stuff here",
    },
  ],
};

export default data;