import bcrypt from "bcryptjs";
const data = {
  users: [
    {
      name: "Justin",
      email: "admin@adminsonly.com",
      password: bcrypt.hashSync("1234", 8),
      isAdmin: true,
    },
    {
      name: "Hank",
      email: "HankHill@stricklandpropane.com",
      password: bcrypt.hashSync("1234", 8),
      isAdmin: false,
    },
  ],
  products: [
    {
      name: "Rona Shirt 2020",
      category: "Shirts",
      image: "/images/prod1.jpg",
      price: 29,
      countInStock: 123,
      brand: "RandoBrand",
      rating: 4.5,
      numReviews: 18,
      description: "good stuff here",
    },
    {
      name: "Meh Shirt",
      category: "Shirts",
      image: "/images/prod2.jpg",
      price: 20,
      countInStock: 10,
      brand: "Zswift",
      rating: 4.5,
      numReviews: 10,
      description: "good stuff here",
    },
    {
      name: "Happy Shirt",
      category: "Shirts",
      image: "/images/prod3.jpg",
      price: 21,
      countInStock: 20,
      brand: "Rand",
      rating: 4.5,
      numReviews: 12,
      description: "good stuff here",
    },
    {
      name: "Boring Shirt",
      category: "Shirts",
      image: "/images/prod4.jpg",
      price: 9,
      countInStock: 0,
      brand: "Ranomadd",
      rating: 4.5,
      numReviews: 11,
      description: "good stuff here",
    },
    {
      name: "Questionable Shirt",
      category: "Pants",
      image: "/images/prod5.jpg",
      price: 30,
      countInStock: 15,
      brand: "Nike",
      rating: 4.5,
      numReviews: 1,
      description: "good stuff here",
    },
    {
      name: "Fleek Shirt",
      category: "Pants",
      image: "/images/prod6.jpg",
      price: 3,
      countInStock: 12,
      brand: "Adidas",
      rating: 4.5,
      numReviews: 17,
      description: "good stuff here",
    },
  ],
};

export default data;
